#!bin/sh

regex='@gmail\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
    echo Your Email $email satisfies policy
    exit 0
else
    echo Your Email $email does not satisfy policy
    exit 1
fi